title: PSPDEV
description: "Development tools for the Playstation Portable"
theme: just-the-docs

# just-the-docs configuration
favicon_ico: /images/pspdev.ico
color_scheme: dark

exclude:
  - README.md
  - Gemfile.lock
